services:
  demo-stream-service:
    build: .
    image: demo-stream-service:dev
    container_name: demo-stream-service
    restart: unless-stopped # Self-healing: restarts if it crashes or server reboots
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate # NEVER use 'update' in prod
    develop:
      watch:
        - action: rebuild
          path: ./src/
        - action: rebuild
          path: ./pom.xml
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/actuator/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

    networks:
      - demo-stream-network

networks:
  demo-stream-network:
    name: demo-stream-network
    driver: bridge
